version: "3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    container_name: app
    volumes:
      - ./app:/usr/src/app
    command: bash -c "python3 /usr/src/app/dbGen.py && flask run --host=0.0.0.0"
